A <%= exception.class.to_s %> occured: <%= exception.message.to_s %>
<% if exception.respond_to?(:backtrace) && exception.backtrace.present? %>
File:                    <%=   exception.backtrace.slice(0, 1).join("\n  ")  %>
<% end %>
<% if ip_info[:ip].present? %>
IP:                      <%= ip_info[:ip] %>
<% end %>
<% if ip_info[:proxy].present? %>
Proxy:                      <%= ip_info[:proxy] %>
<% end %>
<% if rack_session.present? %>
Session:                      <%= rack_session%>
<% end %>
<% if request_path.present? %>
Request URI:             <%= request_path %>
<% end %>
<% if referrer.present? %>
Referer:                 <%= referrer %>
<% end %>
PID:                     <%= process %>
PWD:                     <%= pwd %>
Uname:                   <%= uname %>
Server:                  <%= server %>
Error time:	             <%= timestamp %>
<% if user_agent.present? %>
User Agent:	             <%= user_agent %>
<% end %>
